name: 'Helmsman Deploy'
description: 'A github action running Helmsman'
inputs:
  args:
    description: 'Arguments to apply to helmsman'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}

branding:
  icon: 'anchor'
  color: 'blue'